services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Ayacoo\AwsMeta\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Ayacoo\AwsMeta\EventListener\AfterFileAddedEventListener:
    tags:
      - name: event.listener
        identifier: ayacoo/aws-meta/after-file-added-event-listener
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedEvent
        method: 'setMetadata'
